apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinostocks-frontend-deployment
  namespace: otterpenguin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinostocks-frontend
  template:
    metadata:
      labels:
        app: dinostocks-frontend
    spec:
      containers:
      - name: dinostocks-frontend
        image: matthewjames4187/dinostocks_frontend:latest
        ports:
          - containerPort: 5173
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: REACT_APP_BACKEND_HOST
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: REACT_APP_BACKEND_HOST
          - name: REACT_APP_BACKEND_PORT
            valueFrom:
              configMapKeyRef:
                name: dinostocks-configmap
                key: REACT_APP_BACKEND_PORT
